tolgee/documentation

docs/icu_messge_format.mdx

Hey - awesome project.
I know hacktoberfest is nearly done, but I noticed you placed the tag on some of your repos but not the docs. Maybe you could also enable it here. Otherwise, thanks again.
Just a little typo that I found.

Fixed typo

---

docs/platform/self_hosting/configuration.mdx

The corresponding code changes are WIP - but will arrive shortly

DeepL machine translation configuration

---

docs/platform/self_hosting/configuration.mdx

https://github.com/tolgee/tolgee-platform/pull/1125

feat: Add Google OAuth configuration

---

docs/web/using_with_react/translating.mdx

a small change for better readability :)

fix typo in integrations doc

---

docs/platform/self_hosting/configuration.mdx

Documentation for PR [#1166](https://github.com/tolgee/tolgee-platform/pull/1166)

feat: Add documentation for OAuth2

---

src/pages/roadmap/index.tsx

Updating roadmap for this year!

feat: Update roadmap 2023

---

blog/2023-03-17-figma-plugin.md

This PR adds links to the documentation and GitHub repo to the blog post announcing release of our Figma plugin.

feat: Add links to docs and repo to Figma plugin post

---

package-lock.json
package.json

This PR updates the version of Docusaurus to the most up-to-date.

feat: Update Docusaurus

---

tolgee-cli/project-configuration.mdx

Also clarify where to find the project ID.

fix: update docs for https://github.com/tolgee/tolgee-cli/pull/37

---

src/pages/roadmap/index.tsx

This PR updates the roadmap. Also, I have switched the sorting of done features so that the most recent ones are right under the "What have we done so far..." heading.
**Preview** is available [here](https://deploy-preview-402--tolgee-web.netlify.app/roadmap).

feat: Update Roadmap and switch sorting of done features

---

platform/projects_and_organizations/export.mdx

feat: Add CLI to the Export section

---

platform/self_hosting/configuration.mdx

Closes tolgee/tolgee-platform#1953

docs: update platform config documentation

---

js-sdk/integrations/vue/ssr.mdx
sidebarJsSdk.js

Docs for https://github.com/tolgee/tolgee-js/pull/3367

feat: vue ssr docs

---

src/pages/pricing/pricing.css

Existing UI with issue:
After Fix:

Fix: removed the horizontal scrollbar in pricing page

---

js-sdk/formatting.mdx
js-sdk/integrations/angular/installation.mdx
js-sdk/integrations/react/installation.mdx
js-sdk/integrations/react/next/app_router.mdx
js-sdk/integrations/react/next/app_router_next_intl.mdx
js-sdk/integrations/react/react_native.mdx
js-sdk/integrations/react/ssr.mdx
js-sdk/integrations/vanilla/initialization.mdx
js-sdk/integrations/vue/installation.mdx

Closing https://github.com/tolgee/tolgee-js/issues/3394

feat: improve format-icu plugin docs

---

js-sdk/integrations/i18next/react_integration.mdx

Add a note on installing peer dependencies for i18next-icu, as this is critical

Add a note on installing peer dependencies for i18next-icu

---

blog/2025-01-15-dotnet-resx-import-export.mdx

Updated some descriptions, added subheadings, and added an extra paragraph

chore: Update 2025-01-15-dotnet-resx-import-export.mdx

---

blog/2022-10-03-six-ways-how-to-contribute-to-open-source.md
blog/2023-04-21-free-software-localization.md
blog/2023-07-12-angular-tutorial.md
blog/2023-10-19-whatspot-case-study.md
blog/2024-10-30-how-I-added-localization-to-dobco-using-tolgee.mdx
footer.js
js-sdk/integrations/react/next/app_router.mdx
js-sdk/integrations/react/next/app_router_next_intl.mdx

Fixes after discussion on slack

fix: outdated docs + slack links

---

platform/faq.mdx
platform/self_hosting/running_with_docker.mdx
platform_versioned_docs/version-2.x.x/what_is_tolgee.mdx

- recommended way is to run it with docker compose with the configuration yaml
- removed version from docker files

feat: recommended way is to run it with docker compose with the configuration yaml

---

platform/projects_and_organizations/project_settings.mdx

https://github.com/tolgee/documentation/issues/980

docs: update project settings screenshot to use webp format
