tolgee/documentation

- docs/platform/self_hosting/configuration.mdx
right now it is tricky to find out what the s3.endpoint is supposed to mean - perhaps at least add a note to the aws service endpoints as all other providers will instruct how to set those when creating the bucket
> Add reference to S3 Service Endpoints

- docs/platform/self_hosting/running_with_java.mdx
Also clarifies when Docker is required, and gives instructions on what to do in order to run Tolgee on bare-metal without Docker installed.
> feat: document application.properties

- platform/what_is_tolgee.mdx
This PR fixes incorrect Markdown format of link to the Chrome plugin on the `What is Tolgee` page.
> fix: Link to Chrome plugin on What is Tolgee

- src/pages/roadmap/index.tsx
Add Figma plugin to roadmap as a separate feature and also add Translation Memory management to the roadmap.
> fix: Add Figma plugin and Translation Memory management to roadmap

- src/component/home/Intro.tsx
When I view [the homepage](https://tolgee.io/), I see a scrollbar because the "The revolution is here" component is too wide to fit on my screen. I have fixed this by removing the `w-[100vw]` Tailwind rule on this component.
I encountered this behavior on Windows 10 and 11, Firefox and Chrome, 24" 1920x1080 and 14" 2880x1800 (with 200% DPI scaling).
> fix: Homepage unnecessary scrollbar

- src/component/pageComponents/featurePage/translationAssistance/MachineTranslationFeature.tsx
- src/integrations.tsx
This PR updates the link to Figma docs on the All Integrations page as it makes more sense to link to the "Setup" article rather than the "Usage" article.
Also, I have removed the negative margin-top from the crossed-out price in the Machine Translations credits component:
> feat: Update Figma plugin link and one minor CSS update

- js-sdk/typed_keys.mdx
- js-sdk/typescript.mdx
- sidebarJsSdk.js
https://github.com/tolgee/tolgee-js/pull/3186
Full blown ts errors are not very practical in dev mode, but there is a way how to use this only for intellisense but not for error checking, which I think will be more convenient. So I've put that into docs as well.
> feat: typed translation keys docs

- tolgee-cli/extraction/custom-extractor.mdx
- tolgee-cli/extraction/syncing-strings.mdx
This PR fixes a typo in Tolgee CLI documentation.
> fix: Typo in Tolgee CLI docs

- blog/2023-04-25-naming-translation-keys.md
in the **casing** section of https://tolgee.io/blog/naming-translation-keys#how-to-start-naming-translation-keys camelCase was written with the first letter capitalised, which would be PascalCase, not camelCase.
> docs: fix camelCase that was actually PascalCase

- tolgee-cli/extraction/syncing-strings.mdx
Hey There 👋 
This a sibling PR for https://github.com/tolgee/tolgee-cli/pull/69.
I wasn't sure about what's the best way to document that the glob argument can now accept multiple values. I had multiple ideas:
a) show multiple example commands
---
b) document the argument below the code example
---
c) Use `...` in the examples, like in the [Commander docs](https://github.com/tj/commander.js?tab=readme-ov-file#variadic-option)
---
I went with `c`, because `a` felt too repetitive for every example and `b` looked weird, because I haven't seen arguments documented for other commands. I'm open for suggestions and opinions though:D
> docs(cli): mark that glob arguments can take multiple values

- src/pages/integrations/next.tsx
On the Next.js integration page, the current link about the app router points to a blog post that is outdated. This PR changes the link to point directly to the documentation about the app router integration.
> docs(integrations): link directly to the next.js app router docs

- js-sdk/integrations/react/next/app_router.mdx
Just a small change. The current link in the app router integration page points to the example that uses the pages router.
> docs(integrations): update next.js app router example link

- js-sdk/integrations/vue/installation.mdx
Given that Vite has become the go-to builder for most Vue 3 apps, it's practical to adjust your environment variable syntax to better integrate with Vite's functionality.
> Update installation.mdx for vue

- platform/getting_started/about_tolgee.mdx
note: this is not an exhaustive update, as I have not checked every page in the docs.. but as the "landing page" for the Platform docs, it is one that almost everyone will visit at some point.
> fix: repair some broken doc links in about_tolgee.mdx

- platform/self_hosting/configuration.mdx
This will be properly fixed by tolgee/tolgee-platform#2702 to make the change permanent for the automatic doc generation from the code itself
> fix: Temporary fix for `pricing` relative link

- js-sdk/providing_static_data.mdx
Based on user feedback #support channel on slack
> feat: add notice about staticData to fallback section

- js-sdk/integrations/react/next/app_router.mdx
- js-sdk/integrations/react/next/app_router_next_intl.mdx
- js-sdk_versioned_docs/version-5.x.x/integrations/react/next/app_router_next_intl.mdx
- Added @tolgee/web as a required dependency in the Next.js integration guide
- Simplified the language list configuration example
- Improved clarity and structure of integration steps
> docs: update Next.js integration guides with @tolgee/web dependency and simplified language list

- package-lock.json
- package.json
Upgrades Docusaurus from version 3.7.0 to 3.8.1, bringing performance improvements to local development.
> chore: update Docusaurus dependencies from 3.7.0 to 3.8.1

- platform/shared/_ScreenWrapper.css
- platform/translation_process/ai_translator.mdx
I discovered that one of the documents' images was in an outdated PNG format and wasn't showing up correctly.
> chore: update image format to webp and add spacing in CSS wrapper

- js-sdk/integrations/react/next/app_router_next_intl.mdx
Currently there is a mistake in the docs, causing markdown to render incorrectly. This small patch fixes that.
Image of the issue:
(The `> To gain a comprehensive understanding of how ...` section should be rendered as mardown)
> docs: fix code block
